smart-home-web/Models/ControlSensor/SensorControlViewModel.cs
using Domain.Core.Model;
using Domain.Core.Model.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Models.ControlSensor
{
    public class SensorControlViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsActive { get; set; } = false;

       
    }
}

smart-home-web/Controllers/SensorControlController.cs
using AutoMapper;
using Infrastructure.Business.DTOs;
using Infrastructure.Business.DTOs.Sensor;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using smart_home_web.Models;
using smart_home_web.Models.ControlSensor;
using smart_home_web.Models.SensorViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Controllers
{
    [Route("[controller]/[action]")]
    public class SensorControlController : Controller
    {
        private readonly ISensorControlManager _sensorControlManager;
        private readonly ISensorManager _sensorManager;
        private readonly IMapper _mapper;

        public SensorControlController(ISensorControlManager sensorControlManager ,ISensorManager sensorManager , IMapper mapper)
        {
            _sensorControlManager = sensorControlManager;
            _sensorManager = sensorManager;
            _mapper = mapper;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {
            var data = _sensorControlManager.GetSensorControls();
            var model = _mapper.Map<List<SensorControlDto>, List<SensorControlViewModel>>(data);
            return View(model);
        }
       
        [Authorize]
        [HttpPost]
        public IActionResult Change(int id, bool isActive)
        {
            var result = _sensorControlManager.UpdateById(id,isActive);
            if (!result.Succeeded) return BadRequest();
              
            return Ok();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var result = _sensorControlManager.Delete(id);
            if (!result.Succeeded) return BadRequest();

            return Ok();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {   
            var sensorControl = _sensorControlManager.GetById(id);
             var controlSensors = _sensorManager.GetControlSensors();
            var sensors = _sensorManager.GetSensorsToControl();

             if(sensorControl == null) return View("Error");

            var model = _mapper.Map<SensorControlDto,EditSensorControlViewModel>(sensorControl);
                                  
            ViewBag.modelControlSensors = new SelectList(_mapper.Map<List<SensorDto>, List<SensorViewModel>>(controlSensors), "Id", "Name");
             ViewBag.modelSensors = new SelectList(_mapper.Map<List<SensorDto>, List<SensorViewModel>>(sensors), "Id", "Name");

            return View(model);                                   
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(EditSensorControlViewModel model)
        {
            if (ModelState.IsValid)
            {
                var sensorControl = _mapper.Map<EditSensorControlViewModel, SensorControlDto>(model);
                 var result = _sensorControlManager.Update(sensorControl);
                if (!result.Succeeded) ModelState.AddModelError("", result.Message);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Add()
        {
           
            var controlSensors = _sensorManager.GetControlSensors();
             var sensors = _sensorManager.GetSensorsToControl();
            
            ViewBag.modelControlSensors = new SelectList(_mapper.Map<List<SensorDto>, List<SensorViewModel>>(controlSensors), "Id", "Name");
            ViewBag.modelSensors = new SelectList(_mapper.Map<List<SensorDto>, List<SensorViewModel>>(sensors), "Id", "Name");

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(AddSensorControlViewModel model)
        {
            if (ModelState.IsValid)
            {
                var sensorControl = _mapper.Map<AddSensorControlViewModel, SensorControlDto>(model);
                var result = _sensorControlManager.Add(sensorControl);
                if (!result.Succeeded) ModelState.AddModelError("", result.Message);

                return RedirectToAction("Index");
            }

            return View(model);
        }
    
    }
}

smart-home-web/Views/SensorControl/Add.cshtml
@using smart_home_web.Models.ControlSensor;
@model AddSensorControlViewModel;


<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form asp-action="Add" asp-controller="SensorControl" role="form">
                <h2 class="text-center">Add SensorControl</h2>
                <hr class="colorgraph">
                <div class="form-group">
                    <input asp-for="Name" class="form-control input-lg" placeholder="Name" tabindex="3">
                </div>
                <div class="form-group">
                    <select id="type-select" asp-for="ControlId" asp-items="@ViewBag.modelControlSensors" class="form-control">
                        <option value="">
                            Select an ControlSensor
                        </option>
                    </select>
                </div>
                <div class="form-group">
                    <select id="sensorid" asp-for="SensorId" asp-items="@ViewBag.modelSensors" class="form-control">
                        <option value="">
                            Select an Sensor
                        </option>
                    </select>
                </div>
                <div class="row" id="hide">
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input asp-for="minValue" class="form-control input-lg" placeholder="Min" tabindex="5">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <input asp-for="maxValue" class="form-control input-lg" placeholder="Max" tabindex="6">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success text-center center-block" />
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.js"></script>

@section Scripts {

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

smart-home-web/Views/SensorControl/Edit.cshtml
@using smart_home_web.Models.ControlSensor;
@model EditSensorControlViewModel;


    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <form asp-action="Edit" asp-controller="SensorControl" role="form">
                    <h2 class="text-center">Edit SensorControl</h2>
                    <hr class="colorgraph">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <input asp-for="Name" class="form-control input-lg" placeholder="" tabindex="3">
                    </div>
                    <div class="form-group">
                        <select id="type-select" asp-for="ControlId" asp-items="@ViewBag.modelControlSensors" class="form-control">
                            <option value="">
                                Select an ControlSensor
                            </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select id="type-select" asp-for="SensorId" asp-items="@ViewBag.modelSensors" class="form-control">
                            <option value="">
                                Select an Sensor
                            </option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input asp-for="minValue" class="form-control input-lg" placeholder="Min" tabindex="5">
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input asp-for="maxValue" class="form-control input-lg" placeholder="Max" tabindex="6">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success text-center center-block" />
                        <a asp-controller="SensorControl" asp-action="Index" class="btn btn-primary center-block"><em class="glyphicon glyphicon-arrow-left"></em> Back to SensorControl</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

@section Scripts {
 @await Html.PartialAsync("_ValidationScriptsPartial")
 }

smart-home-web/Views/SensorControl/Index.cshtml
@using smart_home_web.Models.ControlSensor
@model List<SensorControlViewModel>

<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

<div class="app-main">
    <div class="app-main__outer">
        <div class="app-main__inner">
            <div class="app-header header-button-move-up">
                <div class="page-title-heading">
                    Controllers
                    <div class="page-title-subheading opacity-10">
                        <a asp-action="Add" class="btn btn-primary">Add new</a>
                    </div>
                </div>
            </div>
            <div class="app-inner-layout app-inner-layout-page">
                <div class="app-inner-layout__wrapper">
                    <div class="app-inner-layout__content pt-1">
                        <div class="tab-content">
                            <div class="container-fluid">
                                <div class="row">
                                    @foreach (var item in Model)
                                    {<div class="col-lg-2" id="hide_@item.Id">
                                            <div class="card-hover-shadow-2x mb-3 card">
                                                <div class="card-header">
                                                    @item.Name
                                                    <a asp-action="Edit" asp-controller="SensorControl" asp-route-Id="@item.Id" class="ml-auto mr-1">
                                                        <i class="pe-7s-config report-button" style="font-size:20px; margin-right:-5px"></i>
                                                    </a>
                                                    <a id="@item.Id" class="link" onclick="remove(@item.Id)" data-request-url="@Url.Action("Delete", "SensorControl")">
                                                        <i class="pe-7s-close report-button" style="font-size:30px; padding:0px"></i>
                                                    </a>
                                                </div>
                                                <div class="card-body d-flex flex-column align-items-center">
                                                    <input type="hidden" name="id" value="@item.Id" />
                                                    <img src="https://t4.ftcdn.net/jpg/02/27/91/35/240_F_227913547_rHRaLadM6Wj2BtfS5Tu555SSjI7xB33s.jpg" class="card-img-center" width="120" height="120" />
                                                    <div class="input-set-active
                                                         edit_@item.Id
                                                                 @Html.Raw(item.IsActive ? "toggle-shadow" : " ")"
                                                         id="@item.Id"
                                                         style="width:57px"
                                                         data-request-url="@Url.Action("Change", "SensorControl")"
                                                         data-active="@Html.Raw(item.IsActive ? "active" : "inactive")">
                                                        <input type="checkbox"
                                                               @Html.Raw(item.IsActive ? "checked" : " ")
                                                               data-toggle="toggle">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>




<script>

    $(".input-set-active").on("click", function () {
        $(this).toggleClass("toggle-shadow");
        var isActive;
        var item = $(".edit_" + this.id);
        isActive = item.data("active") == "active";
        $.ajax({
            url: "@Url.Action("Change", "SensorControl")",
            data: { 'id': this.id, 'isActive': !isActive },
            type: "post",
            cache: false,
            success: function (savingStatus) {
                item.data("active") = !isActive ? "active" : "inactive";
            },
            error: function (xhr, ajaxOptions, thrownError) {
                window.alert("Error encountered while sending request");
                console.log(thrownError);
            }
        });
    });


    function remove(clicked_id) {
        var url = $('.link').attr('data-request-url');
        $("#hide_" + clicked_id).hide(function () {

        });
        debugger;
        $.ajax({
            url: url,
            data: { 'id': clicked_id },
            type: "post",
            cache: false,

            success: function (savingStatus) {

            },
            error: function (xhr, ajaxOptions, thrownError) {
                window.alert("Error encountered while sending request");
                console.log(thrownError);
            }
        });
    }
</script>