smart-home-web/Controllers/DashboardController.cs
using AutoMapper;
using Domain.Core.Model;
using Infrastructure.Business.DTOs.Dashboard;
using Infrastructure.Business.DTOs.Icon;
using Infrastructure.Business.Infrastructure;
using Infrastructure.Business.Interfaces;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.Dashboard;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Controllers
{
    [Route("[controller]/[action]")]
    public class DashboardController : Controller
    {
        private readonly IMapper _mapper;
        private IHostingEnvironment _env;
        private IDashboardManager _dashboardManager;
        private readonly IIconManager _iconManager;
        private UserManager<AppUser> _userManager;

        public DashboardController(
            IMapper mapper,
            IHostingEnvironment env,
            IDashboardManager dashboardManager,
            IIconManager iconManager,
            UserManager<AppUser> userManager)
        {
            _mapper = mapper;
            _env = env;
            _dashboardManager = dashboardManager;
            _iconManager = iconManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var userId = _userManager.GetUserId(User);
            ViewBag.userid = userId;
            var dashboard = await _dashboardManager.GetById(id);
            if (dashboard != null)
            {
                var result = _mapper.Map<DashboardDto, DashboardViewModel>(dashboard);
                return View(result);
            }
            return NotFound("The dashboard is not found!");
        }


        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            if (User.Identity.IsAuthenticated)
            {
                var uDashs = await _dashboardManager.GetByUserId(userId);
                var pDashs = await _dashboardManager.GetAllPublic(userId);

                var userDashs = _mapper.Map<IEnumerable<DashboardDto>, IEnumerable<DashboardViewModel>>(uDashs);
                var publicDashs = _mapper.Map<IEnumerable<DashboardDto>, IEnumerable<DashboardViewModel>>(pDashs);
                var result = userDashs.Union(publicDashs);

                return View(new DashboardIndexViewModel
                {
                    Dashboards = result.Reverse()
                });
            }
            else
            {
                var dashboards = await _dashboardManager.GetAllPublic(userId);
                var result = _mapper.Map<IEnumerable<DashboardDto>, IEnumerable<DashboardViewModel>>(dashboards);

                return View(new DashboardIndexViewModel
                {
                    Dashboards = result.Reverse()
                });
            }
        }

        [Authorize]
        public IActionResult Create() => ViewComponent("DashboardCreate");

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateDashboardViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            DashboardDto dashboardDto = _mapper.Map<CreateDashboardViewModel, DashboardDto>(model);
            if (model.IconFile != null)
                dashboardDto.IconId = await _iconManager.CreateAndGetIconId(model.IconFile);

            dashboardDto.AppUserId = _userManager.GetUserId(User);

            var res = _dashboardManager.Create(dashboardDto).Result;

            if (res != null)
            {
                DashboardViewModel dashmodel = _mapper.Map<DashboardDto, DashboardViewModel>(res);
                if(!dashmodel.IsPublic)
                    dashmodel.DashCreatorUserName = User.Claims.ElementAt(1).Value;
                return ViewComponent("DashboardElement", dashmodel);
            }
            else
            {
                //ModelState.AddModelError(res.Property, res.Message);
                return View(model);
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(EditDashboardViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            DashboardDto dashboardDto = _mapper.Map<EditDashboardViewModel, DashboardDto>(model);
            IconDto iconDto = null;
            if (model.IconFile != null) 
            {
                dashboardDto.IconId = await _iconManager.CreateAndGetIconId(model.IconFile);
                iconDto = await _iconManager.GetById(dashboardDto.IconId.GetValueOrDefault());
                dashboardDto.IconPath = iconDto.Path;
            }
            dashboardDto.AppUserId = _userManager.GetUserId(User);
            var res = _dashboardManager.Update(dashboardDto).Result;

            if (res != null)
            {
                res = _dashboardManager.GetById(res.Id).Result;
                DashboardViewModel dashmodel = _mapper.Map<DashboardDto, DashboardViewModel>(res);
                if (model.IconFile == null)
                {
                    iconDto = await _iconManager.GetById(dashboardDto.IconId.GetValueOrDefault());
                    dashboardDto.IconPath = iconDto.Path;
                }
                if (!dashmodel.IsPublic)
                    dashmodel.DashCreatorUserName = User.Claims.ElementAt(1).Value;
                return ViewComponent("DashboardElement", dashmodel);
            }
            else
            {
                //ModelState.AddModelError(res.Property, res.Message);
                return View(model);
            }
        }

        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var dashboardDto = await _dashboardManager.GetById(id);
            if (dashboardDto != null)
            {
                EditDashboardViewModel model = _mapper.Map<DashboardDto, EditDashboardViewModel>(dashboardDto);
                return ViewComponent("DashboardEdit", model);
            }
            return ViewComponent("DashboardEdit", null);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var res = await _dashboardManager.Delete(id);
                if (!res.Succeeded)
                {
                    ModelState.AddModelError(res.Property, res.Message);
                    return View();
                }

                return Ok();
            }
            catch
            {
                return View();
            }
        }
    }
}

smart-home-web/Controllers/ProfileController.cs
using AutoMapper;
using Domain.Core.Model;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using smart_home_web.Models;
using smart_home_web.Models.Profile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smart_home_web.Controllers
{
    [Route("[controller]/[action]")]
    public class ProfileController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IIconManager _iconManager;
        private readonly IMapper _mapper;

        public ProfileController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, IIconManager iconManager, IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _iconManager = iconManager;
            _mapper = mapper;
        }

           
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var image = await _iconManager.GetById(user.IconId.Value);
            var model = new ProfileViewModel
            {
                Id = user.Id,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                FirstName = user.FirstName,
                LastName = user.LastName,
                IconPath = image.Path,
                IconId = image.Id
            };

            return View(new IndnexViewModel { ProfileViewModel = model });
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(IndnexViewModel model)
        {
            if (!ModelState.IsValid)            
                return BadRequest("Invalid current password");
            
            var user = await _userManager.GetUserAsync(User);

            if (user == null)            
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, model.ChangeProfilePasswordViewModel.OldPassword, model.ChangeProfilePasswordViewModel.NewPassword);

            if (!changePasswordResult.Succeeded)           
              return BadRequest(changePasswordResult.Errors.ToString());
            

            await _signInManager.SignInAsync(user, isPersistent: false);           
          
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> Update(IndnexViewModel model)
        {
            if (!ModelState.IsValid)
               return Ok();

            var user = await _userManager.GetUserAsync(User);
          
            if (model.ProfileViewModel.IconFile != null) {
               var id  =await _iconManager.CreateAndGetIconId(model.ProfileViewModel.IconFile);
                user.IconId = id;
            }                      
            user.Email = model.ProfileViewModel.Email;
            user.PhoneNumber = model.ProfileViewModel.PhoneNumber;
            user.FirstName = model.ProfileViewModel.FirstName;
            user.LastName = model.ProfileViewModel.LastName;             
            

             var result =  _userManager.UpdateAsync(user);

            if (!result.Result.Succeeded) return BadRequest();

            return Ok();
        }
    }
}

smart-home-web/Controllers/SensorController.cs
using AutoMapper;
using Domain.Core.Model;
using Domain.Core.Model.Enums;
using Infrastructure.Business.DTOs.Sensor;
using Infrastructure.Business.DTOs.SensorType;
using Infrastructure.Business.Managers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using smart_home_web.Models.SensorType;
using smart_home_web.Models.SensorViewModel;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Infrastructure.Business.DTOs.Icon;

namespace smart_home_web.Controllers
{
    [Route("[controller]/[action]")]
    public class SensorController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ISensorManager _sensorManager;
        private readonly IIconManager _iconManager;
        private readonly ISensorTypeManager _sensorTypeManager;
        private readonly UserManager<AppUser> _userManager;
        private IHostingEnvironment _env;

        public SensorController(IMapper mapper,
            ISensorManager sensorManager,
            IIconManager iconManager,
            ISensorTypeManager sensorTypeManager,
            UserManager<AppUser> userManager,
            IHostingEnvironment env)
        {
            _sensorManager = sensorManager;
            _sensorTypeManager = sensorTypeManager;
            _iconManager = iconManager;
            _mapper = mapper;
            _userManager = userManager;
            _env = env;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                string userId = _userManager.GetUserId(HttpContext.User);
                IEnumerable<SensorViewModel> sensors = _mapper.Map<IEnumerable<SensorViewModel>>(await _sensorManager.GetAllSensorsByUserIdAsync(userId));
                return View(sensors.Reverse());
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            IEnumerable<SensorTypeDto> sensorTypeDtos = _sensorTypeManager.GetAllSensorTypesAsync().Result;
            var sensorTypes = _mapper.Map<IEnumerable<SensorTypeDto>, IEnumerable<SensorTypeViewModel>>(sensorTypeDtos);
            ViewBag.sensorTypes = sensorTypes;
            ViewBag.loggedUserId = _userManager.GetUserId(HttpContext.User);
            return ViewComponent("SensorCreate");
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(CreateSensorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            SensorDto sensorDto = _mapper.Map<CreateSensorViewModel, SensorDto>(model);
            SensorTypeDto sensorType = await _sensorTypeManager.GetSensorTypeByIdAsync(sensorDto.SensorTypeId);
            if (model.IconFile != null)
            {
                sensorDto.IconId = await _iconManager.CreateAndGetIconId(model.IconFile);
            }
            else
            {

                sensorDto.IconId = sensorType.IconId;
            }

            var res = await _sensorManager.Create(sensorDto);

            if (res != null)
            {
                res.SensorTypeName = sensorType.Name;
                return ViewComponent("SensorElement", _mapper.Map<SensorDto, SensorViewModel>(res));
            }
            else
            {
                //ModelState.AddModelError(res.Property, res.Message);
                return View(model);
            }
        }

        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var sensorDto = await _sensorManager.GetSensorByIdAsync(id);
            if (sensorDto != null)
            {
                EditSensorViewModel sensorViewModel = _mapper.Map<SensorDto, EditSensorViewModel>(sensorDto);
                return ViewComponent("SensorEdit", sensorViewModel);
            }
            return ViewComponent("SensorEdit", null);

        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditSensorViewModel model)
        {
            SensorDto sensorDto = _mapper.Map<EditSensorViewModel, SensorDto>(model);
            IconDto iconDto = null;
            if (model.IconFile != null)
            {
                sensorDto.IconId = _iconManager.CreateAndGetIconId(model.IconFile).Result;
                iconDto = await _iconManager.GetById(sensorDto.IconId.GetValueOrDefault());
                sensorDto.IconPath = iconDto.Path;
            }

            var res = await _sensorManager.Update(sensorDto);

            if (res != null)
            {
                res = await _sensorManager.GetSensorByIdAsync(sensorDto.Id);
                iconDto = await _iconManager.GetById(sensorDto.IconId.GetValueOrDefault());
                sensorDto.IconPath = iconDto.Path;
                sensorDto.SensorTypeName = res.SensorTypeName;
                return ViewComponent("SensorElement", _mapper.Map<SensorDto, SensorViewModel>(sensorDto));
            }
            else
            {
                //ModelState.AddModelError(res.Property, res.Message);
                return View(model);
            }
        }

        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var res = await _sensorManager.Delete(id);
                if (!res.Succeeded)
                {
                    ModelState.AddModelError(res.Property, res.Message);
                    return View();
                }

                return Ok();
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetSensorsByReportElementType(ReportElementType type, int dashboardId)
        {
            var res = await _sensorManager.GetSensorsByReportElementType(type, dashboardId);
            if (res.Count == 0)
                return BadRequest();
            return Ok(res);
        }

        [HttpPost]
        public async Task<IActionResult> SetActive(int id)
        {
            await _sensorManager.SetActive(id);
            return Ok();
        }
    }
}

smart-home-web/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - smart_home_web</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="/main.07a59de7b920cd76b874.css" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>
<body>
    @RenderBody()
    @RenderSection("Scripts", required: false)
</body>
</html>

smart-home-web/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/nice-select/dist/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/ReportElement.css" rel="stylesheet" />
    <link href="/main.07a59de7b920cd76b874.css" rel="stylesheet">
    <link href="~/lib/toastr/toastr.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gridstack@0.6.0/dist/gridstack.min.css" />
    <link href="~/css/OnOff.css" rel="stylesheet" />

    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    @*<script src="~/js/dashboard.js"></script>*@
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script>
        // TOASTR OPTIONS
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "50000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/message.js"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gridstack@0.6.0/dist/gridstack.all.js"></script>
    <script type="text/javascript" src="~/assets/scripts/main.07a59de7b920cd76b874.js"></script>
    <script src="~/js/Graph.js"></script>
    <script src="~/js/update-report-elements.js"></script>
</head>
<body>
    <div class="app-container app-theme-gray">
        <partial name="_NavbarPartial" />
        <partial name="_HeaderPartial" />
            @RenderBody()
        </div>
</body>
</html>

smart-home-web/Views/Shared/_HeaderPartial.cshtml
@using Domain.Core.Model;
@using Microsoft.AspNetCore.Identity
@using smart_home_web.Models;


@inject SignInManager<AppUser> SignInManager;
@inject UserManager<AppUser> UserManager;



<div class="app-header" style="margin-left: auto; width: auto;">
    <div class="app-header-right">
        @if (User.Identity.IsAuthenticated)
        {
            @*<partial name="_Bell" />
            <div class="header-btn-lg pr-0">
                <div class="widget-content p-0">
                    <div class="widget-content-wrapper">
                        <div class="widget-content-left">
                            <div class="btn-group">
                                <a asp-controller="Profile" asp-action="Index" class="p-0 btn">
                                    <img width="42" class="rounded" src="https://i.imgur.com/f2kiwyi.png" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>*@
        }
        else
        {
            <a asp-action="Login" asp-controller="Account" class="btn-wide btn-outline-2x mr-md-2 btn btn-outline-focus btn-sm">
                Log In
            </a>
        }
    </div>
</div>
<div class="app-header-overlay d-none animated fadeIn"></div>

smart-home-web/Views/Shared/_HistoryLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - smart_home_web</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="/main.07a59de7b920cd76b874.css" rel="stylesheet">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">


    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>
<body>
    <div class="app-container app-theme-gray">
        <partial name="_NavbarPartial" />
        <partial name="_HeaderPartial" />
            @RenderBody()
    </div>
</body>
</html>

smart-home-web/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - smart_home_web</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/lib/toastr/toastr.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/css/site.css">
    <link href="/main.07a59de7b920cd76b874.css" rel="stylesheet">

</head>
<body>
    <div class="app-container app-theme-gray">
        <partial name="_NavbarPartial">
            <partial name="_HeaderPartial">
                @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    <script src="~/lib/toastr/toastr.min.js"></script>
    <script>
        // TOASTR OPTIONS
        toastr.options =
        {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "50000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
    
    <script type="text/javascript" src="~/assets/scripts/main.07a59de7b920cd76b874.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/message.js"></script>

    <script src="~/js/Graph.js"></script>
    <script src="~/js/update-report-elements.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

smart-home-web/Views/Shared/_NavbarPartial.cshtml
@using Domain.Core.Model;
@using Microsoft.AspNetCore.Identity
@using smart_home_web.Models;


@inject SignInManager<AppUser> SignInManager;
@inject UserManager<AppUser> UserManager;

@{
        var loggedIn = User.Claims.Any();
        if (loggedIn)
        {
        <div class="app-sidebar-wrapper">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
                    <a asp-area="" asp-controller="Dashboard" asp-action="Index" data-toggle="tooltip" data-placement="bottom" title="" class="logo-src" data-original-title=""></a>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu metismenu">

                            <li class="mm-active">
                                <a href="#" aria-expanded="true">
                                    <i class="metismenu-icon pe-7s-display2"></i>
                                    <span>Dashboards</span>
                                    <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                </a>
                                <ul class="mm-collapse mm-show" style="">
                                    <li>
                                        <a asp-area="" asp-controller="Dashboard" asp-action="Index">All Dashboards</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="mm-active">
                                <a href="#" aria-expanded="true">
                                    <i class="metismenu-icon pe-7s-signal"></i>
                                    <span>Sensors</span>
                                    <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                </a>
                                <ul class="mm-collapse mm-show" style="">
                                    <li>
                                        <a asp-area="" asp-controller="Sensor" asp-action="Index">All Sensors List</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="SensorType" asp-action="Index">All Sensors Types</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="SensorControl" asp-action="Index">Sensors Control Panel</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="mm-active">
                                <a href="#" aria-expanded="true">
                                    <i class="metismenu-icon pe-7s-browser"></i>
                                    <span>Histories</span>
                                    <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                </a>
                                <ul class="mm-collapse mm-show" style="">
                                    <li>
                                        <a asp-area="" asp-controller="History" asp-action="Index">Histories List</a>
                                    </li>
                                </ul>
                            </li>
                            @*<li class="mm-active">
                                <a href="#" aria-expanded="true">
                                    <i class="metismenu-icon pe-7s-note2"></i>
                                    <span>Notifications</span>
                                    <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                </a>
                                <ul class="mm-collapse mm-show" style="">
                                    <li>
                                        <a asp-area="" asp-controller="Toast" asp-action="Index">All Notifications</a>
                                    </li>
                                </ul>
                            </li>*@
                            <li class="mm-active">
                                <a href="#" aria-expanded="true">
                                    <i class="metismenu-icon pe-7s-users"></i>
                                    <span>Account</span>
                                    <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                </a>
                                <ul class="mm-collapse mm-show" style="">
                                    <li>
                                        <a asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="app-sidebar-overlay d-none animated fadeIn"></div>
    }
}